---
- name: base playbook
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - include_tasks: "profiles/base.yml"

    - block:
      - include_tasks: "profiles/{{ profile }}.yml"
        tags: ['profile']
      when: profile is defined
