---
- name: base playbook
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: default packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - zsh

