---
- name: base playbook
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: default packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - zsh
        - tmux
        - git
    - block:
      - include_tasks: "tasks/{{ profile }}.yml"
      when: profile is defined
