---
- name: base playbook
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: default packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - zsh
        - tmux
        - git
      tags: ['packages']

    - include_tasks: "tasks/users.yml"
      tags: ['users']

    - include_tasks: "tasks/sudo.yml"
      tags: ['sudo']

    - block:
      - include_tasks: "tasks/{{ profile }}.yml"
        tags: ['profile']
      when: profile is defined
