- name: kubernetes cluster on rpi
  hosts: pikube
  become: true
  tasks:
    # need a docker role that will work with rpi
    #    - import_role:
    #    name: ansible-role-docker #
    #  tags: docker
    - import_role:
        name: ansible-k8s
      tags: k8s
