- src: https://github.com/elastic/ansible-elasticsearch.git
  version: 50a8f3b144d6e1714db0431a36bab2a11f121f74

- src: https://github.com/hmm01i/ansible-grafana.git
  version: fixes

- src: https://github.com/jtyr/ansible-config_encoder_filters.git
  name: config_encoder_filters
  version: dc3a089e7a2b94d38fc1d725272966ef37d57f5f

- src: https://github.com/mongrelion/ansible-role-docker.git
  version: 075ceb9b73e6751f8cd0c174978bad9bf97a2ecc

- src: https://github.com/willshersystems/ansible-sshd.git
  version: d2ba81107ade1cf53c8b93590465c21ad2bc4530

    # we don't want to pull this yet. its under development locally
  #- src: https://github.com/hmm01i/ansible-k8s.git
  #  version: rpi
  #
- src: https://github.com/PowerDNS/pdns-ansible.git
  version: bfabe2adca8dcd3c848204a09cb52e36741675ee

- src: https://github.com/cloudalchemy/ansible-prometheus.git
  version: 0a9d99e6ff8ff5052b09c977ff89a2fc8098c265

- src: https://github.com/cloudalchemy/ansible-node-exporter.git
  version: 0373b7507436f48fbc4f6a5ea3f835d01be663b9
