---
- name: manage a user
  hosts: "{{targets}}"
  become: true
  tasks:
    - name: "add user | {{ username }}"
      user:
        name: "{{ username }}"
      #    uid: 5000 #TODO: fix this... do we care?
        state: present
        password: "{{ user_password |password_hash('sha512') }}"

  vars_prompt:
    - name: "username"
      prompt: "Enter user to manage"
      private: no

    - name: "user_password"
      prompt: "Enter password"
      private: yes
      confirm: yes

