---
- import_role:
    name: ansible-prometheus
  tags: ['prometheus']
  vars:
    prometheus_components:
      - prometheus
    prometheus_version: 2.3.1


- import_role:
    name: config_encoder_filters

- import_role:
    name:  ansible-grafana

